#!zsh

rm -R build
rm -R dist
# pyinstaller epidemic.py --onedir --windowed -y --add-data "data/cards.yml:data" --add-data "img/pandemic-logo.png:img" --icon=icon.icns --name='Epidemic'
pyinstaller Epidemic.spec