"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pandemic.py']
DATA_FILES = ['img/pandemic-logo.png']
OPTIONS = {'iconfile': 'icon.icns'}

setup(
    app=APP,
    name="Pandemic Deck Tracker",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
